### ISSUE TITLE
Autogenerate a dag for the data toml

### ISSUE THREAD

**Issue by Emiller88** [tecosaur/DataToolkitBase.jl#6]
Thought this might be a cool feature. 

Example

https://www.nextflow.io/docs/latest/tracing.html#dag-visualisation
https://snakemake.readthedocs.io/en/v5.32.0/tutorial/basics.html?highlight=dag#step-4-indexing-read-alignments-and-visualizing-the-dag-of-jobs

**Comment by tecosaur** [comment]
I don't know if you've seen https://github.com/tecosaur/DataToolkitBase.jl/blob/main/ext/AbstractTreesExt.jl, but we could do something similar and support creating a Graphs.jl `DiGraph`, which could then be rendered with GraphMakie.jl or similar..

**Comment by tecosaur** [comment]
Implemented in 2d04fa47818a87b3c74a2472b0cf7642a082bb71 as a `MetaGraphsNext` extension.
